### ISSUE TITLE
Templates must be viewed before they are watched

### ISSUE THREAD

**Issue by jsumners** [jsumners/hapi-marko#2]
When hot reloading is enabled, templates are not monitored for changes prior to them being "viewed". There should be a mechanism to register the templates to watch on server initialization.

**Comment by patrick-steele-idem** [comment]
Hey @jsumners, if you use [chokidar](https://github.com/paulmillr/chokidar) then it will watch new directories and new files as they are added. It provides a much more robust file watching solution than the file watching service provided by the native `fs` module.

Also, I recommend taking a look at [browser-refresh](https://github.com/patrick-steele-idem/browser-refresh). `browser-refresh` is a process launcher like `nodemon` that starts a file watching service out of the main application process. If you use `browser-refresh` then you will get support for hot reloading and automatic browser refreshing for free with minimal code change required in the application code.

**Comment by jsumners** [comment]
@patrick-steele-idem my issue with chokidar is the reliance on node-gyp. The project I wrote this for needs to be dependent solely on the V8 engine.

**Comment by patrick-steele-idem** [comment]
Hi @jsumners, makes sense. One reason I prefer the `browser-refresh` approach is that the `browser-refresh` module keeps the file watching code (and `chokidar`) out of the application code, but I understand that you are building a module for developers who don't necessarily use or know of `browser-refresh`.

**Comment by jsumners** [comment]
I might be one of them ;)

But since we're discussing it: I have found `marko/hot-reload` doesn't actually invalidate the compiled templates. It seems to only invalidate the in-memory(?) cache via `require.cache`. Which is leading to the old template still being served after editing the source `.marko` file. Is this correct?

**Comment by jsumners** [comment]
Fixed in commit 7260a99

**Comment by patrick-steele-idem** [comment]
Hey @jsumners, did you figure it out? `marko` includes tests to make sure the hot-reload feature works correctly and we are not seeing any issues. Here's a link to the relevant tests: https://github.com/raptorjs/marko/blob/master/test/hot-reload-test.js

Please let me know if you are still seeing issues.

**Comment by jsumners** [comment]
@patrick-steele-idem Your test isn't covering this situation:

**layout.marko**:
```html
<div class="container">
  <include template="foo.marko"/>
</div>
```

**foo.marko**:
```html
Hello ${data.name}
```

Load `layout.marko`, render it, and see something like "Hello James". Now, modify `foo.marko` to:

```html
<p>Hello ${data.name}</p>
```

And then re-render `layout.marko` after invoking `handleFileModified` on it. You'll still see "Hello James" instead of "<p>Hello James</p>".

**Comment by jsumners** [comment]
No, I see how it's working. You're relying on the application that is using `marko` to handle all of the expirations. That's tricky when you start including templates with the `include` directive since the included template is never directly requested through the parent application. Such templates are only ever handled by the `marko` engine itself.

My personal opinion is that a template engine should be handling the templates -- right down to reloading any of them that changed. But I resolved the issue in my case with some extra file watching (instead of just watching the templates that have been requested).
